### ISSUE TITLE
isValidAddCommand does not treat list of allergies as 1 input.

### ISSUE THREAD

**Issue by yuki-zmstr** [AY2324S2-CS2113-W14-2/tp#119]
![Screenshot 2024-04-04 at 5 12 08 PM](https://github.com/AY2324S2-CS2113-W14-2/tp/assets/72074553/ec17660d-69d8-4aca-b1f3-b80aca556512)

The command validator treats each allergy as 1 parameter. In the above example, the validator passes, even though the url is not there.

**Comment by nidhi-nayak** [comment]
wait little confused on this. i dont understand how? it's erroring because there is no url (URL_INDEX var is 5). so its treating "egg dairy" as one parameter of allergies? 

i might have interpretted this wrong though. do you mind explaining it a bit more. i'll get started on working on a solution once i understand what's wrong. (of course i should add some error handling and a better message rather than the index out of bounds error) @yuki-zmstr

**Comment by nidhi-nayak** [comment]
never mind! i see your point! fixed!
